In [1]:
import numpy as np

In [6]:
from __future__ import division

In [8]:
5/2

2.5

In [17]:
arr1 = np.array([np.arange(1,5), np.arange(8,12)])

In [18]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [19]:
arr1*arr1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [20]:
arr1**2

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [21]:
arr1 - 1

array([[ 0,  1,  2,  3],
       [ 7,  8,  9, 10]])

In [22]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [23]:
arr1-arr1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [24]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [25]:
1 / arr1

array([[ 1.        ,  0.5       ,  0.33333333,  0.25      ],
       [ 0.125     ,  0.11111111,  0.1       ,  0.09090909]])

In [28]:
arr1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [ ]:
arr1