In [1]:
import numpy as np

In [2]:
arr = np.arange(5)

In [3]:
arr

array([0, 1, 2, 3, 4])

In [4]:
# Save the array to myarray
np.save('myarray', arr)

In [5]:
arr = np.arange(10)

In [6]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
# Load the array from file
np.load('myarray.npy')

array([0, 1, 2, 3, 4])

In [9]:
array1 = np.load('myarray.npy')
array1

array([0, 1, 2, 3, 4])

In [11]:
array2 = arr
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Save multiple arrays
# Save as a dictionary, key 'x' is array1, key 'y' is array2
np.savez('ziparray.npz', x=array1, y=array2)

In [18]:
# Load multiple arrays
archive_array = np.load('ziparray.npz')

In [23]:
archive_array['x']

array([0, 1, 2, 3, 4])

In [24]:
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [27]:
# Save array as text file
np.savetxt('mytextarray.txt', arr, delimiter=',')

In [32]:
arr = np.loadtxt('mytextarray.txt', delimiter=',')
arr

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])