In [1]:
import numpy as np

In [2]:
my_list1 = [1,2,3,4]

In [3]:
my_array1 = np.array(my_list1)

In [4]:
my_array1

array([1, 2, 3, 4])

In [5]:
my_list2 = [11,22,33,44]

In [6]:
my_lists = [my_list1, my_list2]

In [8]:
my_array2 = np.array(my_lists)

In [9]:
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [10]:
my_array2.shape

(2, 4)

In [11]:
my_array2.dtype

dtype('int64')

In [12]:
my_array2[0]

array([1, 2, 3, 4])

In [13]:
my_array2[0][1] = 0

In [14]:
my_array2[0]

array([1, 0, 3, 4])

In [15]:
my_array2[0][1] = 2

In [16]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [20]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [21]:
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [22]:
my_zeros_array = np.zeros(5)

In [23]:
my_zeros_array.dtype

dtype('float64')

In [24]:
np.ones([5,5])

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [25]:
np.zeros([5,5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [26]:
np.empty(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [27]:
np.empty([5,5])

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [28]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [29]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [31]:
np.arange(5, 0)

array([], dtype=int64)

In [32]:
np.arange(5, 100000, 2)

array([    5,     7,     9, ..., 99995, 99997, 99999])

In [33]:
len(np.arange(5, 100000, 2))

49998